[build-system]
# dynamic version
requires = ["setuptools>=61", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "jaxsnn"
dynamic = ["version"]
authors = [
  { name="Electronic Vision(s)", email="visions-dev@kip.uni-heidelberg.de" },
]
description = "jaxsnn is an event-based approach to machine-learning-inspired training and simulation of SNNs, including support for neuromorphic backends (BrainScaleS-2)."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
  "jax>=0.4.13",
  "jaxlib>=0.4.13", # ECM: not sure if still needed
  "scipy",
  "optax>=0.1.4",
  "tree-math>0.1.0",
  "matplotlib",
  "networkx",
]

[project.optional-dependencies]
nir = ["nir>=1.0.8"]
test = ["pytest"]
test-nir = ["pytest", "nir>=1.0.8"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
testpaths = ["tests/sw"]

[project.urls]
Homepage = "https://github.com/electronicvisions/jaxsnn"
"Bug Tracker" = "https://github.com/electronicvisions/jaxsnn/issues"

[tool.setuptools.packages.find]
where = ["src/pyjaxsnn"]
include = ["jaxsnn*"]

[tool.setuptools_scm]
fallback_version = "0.2.0"
version_scheme = "no-guess-dev"
