@Library("jenlib") _

withCcache() {
	wafDefaultPipeline(projects: ["jax-snn"],
	                   container: [app: "dls-core"],
	                   configureInstallOptions: "--build-profile=ci",
	                   notificationChannel: "#softies")
}
