@Library("jenlib")

withCcache() {
	wafDefaultPipeline(projects: ["jax-snn"],
	                   container: [app: "dls-core"],
	                   configureInstallOptions: "--build-profile=ci",
	                   notificationChannel: "#jenkins-trashbin")
}
